POST http://localhost:4070/create
Content-Type: application/json

{
    "nome": "Leonardo",
    "cpf": "2452585",
    "senha": "123456" 
}

###
GET http://localhost:4070/login/351329898

###
PUT http://localhost:4070/uptadeKey?search=2452585
Content-Type: application/json

{
    "senha": "9828135498265"
}

###
GET  http://localhost:4070/listPersons

###