POST http://localhost:4070/create
Content-Type: application/json

{
    "nome": "Leonardo",
    "cpf": "651565",
    "senha": "123456" 
}

###
GET http://localhost:4070/login/651565

###
PUT http://localhost:4070/uptadeKey?search=651565
Content-Type: application/json

{
    "senha": "9865"
}

###
GET  http://localhost:4070/listPersons

###